mysite/goldbankapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url,include

app_name = 'goldbankapp'

urlpatterns =[
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include
from goldbankapp import views

urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('goldbankapp.urls')),
        path('base/',views.base,name='base'),
        path('features/',views.features,name='features'),
        path('adminPanel/',views.adminPanel,name='adminPanel'),
        path('',views.home,name='home'),
        #path('goldbankapp/', include('goldbankapp.urls')),
        path('logout/', views.user_logout, name='logout'),
        path('about/',views.about, name="about"),
        path('moneytogold/',views.moneytogold, name='moneytogold'),
        path('moneytogold/conv/',views.conv, name='conv'),
        #path('gold_price/',views.gold_price, name='gold_price'),
        path('gold_price/',views.updatePrice, name='updatePrice'),
        path('update_profile/',views.updateProfile, name='updateProfile'),
        path('profile_pic/',views.profile_pic, name='profile_pic'),
        path('show_gold_price/',views.show_gold_price, name='show_gold_price'),
        path('user_profile/',views.user_profile, name='user_profile'),
        path('show_account_info/',views.show_account_info, name='show_account_info'),
        path('show_balance_info/',views.show_balance_info, name='show_balance_info'),
        path('show_loan_info/',views.show_loan_info, name='show_loan_info'),
        path('show_purchase_info/',views.show_purchase_info, name='show_purchase_info'),
        path('show_deposit_history/',views.show_deposit_history, name='show_deposit_history'),
        path('show_withdraw_history/',views.show_withdraw_history, name='show_withdraw_history'),
        #path('acc_no/',views.acc_no,name='acc_no'),
        path('depositamount/',views.depositamount,name='depositamount'),
        path('withdrawamount/',views.withdrawamount,name='withdrawamount'),
        path('bankTotalMoney/',views.bankTotalMoney,name='bankTotalMoney'),
        path('loan/',views.loanamount,name='loanamount'),
        path('return_loan/',views.loan_return,name='loan_return'),
        path('transfer_gold/',views.transfer_gold,name='transfer_gold'),
        path('admin_login/',views.admin_login,name='admin_login'),
        path('buy_product/',views.product,name='product'),
        path('buy_gold/',views.buy_gold,name='buy_gold'),
        path('buy_silver/',views.buy_silver,name='buy_silver'),
        path('buy_bronze/',views.buy_bronze,name='buy_bronze'),
        path('myPanel/',views.myPanel, name='myPanel')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/goldbankapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo, priceOfGold


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
        help_texts = {
            'username': None,
        }

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('mobileNo', 'location', 'dateofbirth',)
        labels = {
            "mobileNo": "Mobile No.:",
            "location": "Home District:",
            "dateofbirth": "Date of Birth:"
        }
        help_texts = {
            'mobileNo': '<small style="color:teal">not mendatory</small>',
            'location': '<small style="color:teal">not mendatory</small>',
            'dateofbirth': '<small style="color:teal">not mendatory</small>',
        }
        widgets = {'dateofbirth': forms.SelectDateWidget(years=range(1900, 2021))}

class updatePriceForm(forms.ModelForm):
    class Meta():
        model = priceOfGold
        fields = ('serial', 'date', 'gold_price',)
        labels = {
            "serial": "Serial:",
            "date": "Enter date:",
            "gold_price": "Gold Price:"
        }
        widgets = {'date': forms.SelectDateWidget(years=range(1900, 2022))}

class profilePicForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)
        labels = {
            "profile_pic": "Profile Photo:"
        }

# class updateProfileForm(forms.ModelForm):
#     class Meta():
#         model = UserProfileInfo
#         fields = ('first_name', 'last_name', 'email', 'mobileNo', 'location', 'dateofbirth')
#         labels = {
#             "email": "Email address:",
#             "mobileNo": "Mobile No:",
#             "location": "Home district:",
#             "dateofbirth": "Date of birth:"
#         }
#         widgets = {'dateofbirth': forms.SelectDateWidget(years=range(1900, 2021))}

mysite/goldbankapp/views.py
import copy
import random

from django.contrib import messages
from django.contrib.auth.models import User
from django.utils import timezone

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import UserForm, UserProfileInfoForm, updatePriceForm, profilePicForm
from .models import priceOfGold, deposit, UserProfileInfo, bankMoney, loan, products, deposit_history, withdraw_history
from django.shortcuts import render
import datetime


def home(req):
    # update = 0
    # try:
    #     update = priceOfGold.objects.last()
    # except priceOfGold.DoesNotExist:
    #     pass
    return render(req, 'home.html')


def base(req):
    return render(req, 'base.html')


def product(req):
    update = priceOfGold.objects.last()
    temp = 5 * float(update.gold_price)
    temp2 = float(5 * 87)
    temp3 = float(5 * 67)
    return render(req, 'buy_product.html',{'temp': temp, 'temp2': temp2, 'temp3': temp3})


def features(request):
    return render(request, 'features.html')


def adminPanel(request):
    return render(request, 'adminPanel.html')


def admin_login(request):
    isadmin = 'a'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_staff:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)
                return HttpResponseRedirect(reverse('adminPanel'))

            else:
                isadmin = 'b'
                return render(request, 'admin_login.html',{'isadmin': isadmin})
        else:
            isadmin = 'c'
            return render(request, 'admin_login.html', {'isadmin': isadmin})
    return render(request, 'admin_login.html', {'isadmin': isadmin})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'registration.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})



def user_login(request):
    isuser = 'a'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_staff == False:
                if user.is_active:
                    login(request, user)
                    if not remember_me:
                        request.session.set_expiry(0)
                    return HttpResponseRedirect(reverse('features'))

                else:
                    return HttpResponse("Account is Not Active.")
            elif user.is_staff == True:
                if user.is_active:
                    isuser = 'staff_user'
                    login(request, user)
                    if not remember_me:
                        request.session.set_expiry(0)
                    return HttpResponseRedirect(reverse('adminPanel'))
                else:
                    return HttpResponse("Account is Not Active.")
        else:
            isuser = 'b'
            return render(request, 'user_login.html',{'isuser': isuser})

    return render(request, 'user_login.html', {'isuser': isuser})



def about(request):
    return render(request, 'about.html')



def moneytogold(request):
    return render(request, 'moneytogold.html')



def conv(request):
    update = priceOfGold.objects.last()
    val1 = int(request.GET['num1'])
    res = (1 / update.gold_price) * val1
    return render(request, 'convert.html', {'result': res, 'amount': val1, 'update': update})



# def gold_price(request):
#     return render(request, 'gold_price.html')

def updatePrice(request):
    if request.method == 'POST':
        updatePrice_form = updatePriceForm(data=request.POST)

        if updatePrice_form.is_valid():
            profile = updatePrice_form.save(commit=False)
            profile.save()
            messages.info(request, 'Price is Updated Successfully :)')

        else:
            print(updatePrice_form.errors)
    else:
        updatePrice_form = updatePriceForm()

    return render(request, 'gold_price.html',
                  {'updatePrice_form': updatePrice_form})


def updateProfile(request):
    registered = 'a'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        mobileNo = request.POST.get('mobileNo')
        location = request.POST.get('location')
        dateofbirth = request.POST.get('dateofbirth')
        mydata = UserProfileInfo()
        mydata.first_name = first_name
        mydata.last_name = last_name
        mydata.email = email
        mydata.mobileNo = mobileNo
        mydata.location = location
        mydata.dateofbirth = dateofbirth

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                try:
                    t = UserProfileInfo.objects.get(user=request.user)
                    t2 = User.objects.get(username=username)
                    # t.first_name = first_name
                    # t.last_name = last_name
                    # t.email = email
                    t.mobileNo = mobileNo
                    t.location = location
                    t.dateofbirth = dateofbirth
                    t.save()
                    t2.first_name = first_name
                    t2.last_name = last_name
                    t2.email = email
                    t2.save()
                except UserProfileInfo.DoesNotExist:
                    z ='z'
                registered = 'b'
        else:
            registered = 'c'

    return render(request, 'update_profile.html', {'registered': registered})


def profile_pic(request):
    if request.method == 'POST':
        form = profilePicForm(request.POST, request.FILES)
        if form.is_valid():
            t = UserProfileInfo.objects.get(user=request.user)
            t.profile_pic = form.cleaned_data['profile_pic']
            t.save()
            #img_obj = form.instance
            return render(request, 'profile_pic.html', {'form': form, 't': t})
    else:
        form = profilePicForm()
    return render(request, 'profile_pic.html', {'form': form})



def show_gold_price(request):
    shgd = priceOfGold.objects.all()
    return render(request, 'show_gold_price.html', {'shgd': shgd})


def user_profile(request):
    return render(request, 'user_profile.html')


def show_account_info(request):
    if request.user.is_authenticated:
        try:
             acinfo = UserProfileInfo.objects.filter(user=request.user)
             t = UserProfileInfo.objects.get(user=request.user)

             date_format = '%Y-%m-%d'
             a = datetime.datetime.strptime(str(datetime.date.today()), date_format)
             b = datetime.datetime.strptime(str(t.currentdate), date_format)
             t.account_age = (a - b).days
             t.save()
             return render(request, 'show_account_info.html', {'acinfo': acinfo, 't': t})
        except UserProfileInfo.DoesNotExist:
             return render(request, 'show_account_info.html', {'acinfo': acinfo})
             #return None
    acinfo = 0
    return render(request, 'show_account_info.html', {'acinfo': acinfo})


def show_balance_info(request):
    if request.user.is_authenticated:
        try:
            bainfo = deposit.objects.filter(username=request.user)
            t = deposit.objects.get(username=request.user)

            t2 = UserProfileInfo.objects.get(user=request.user)
            date_format = '%Y-%m-%d'
            a = datetime.datetime.strptime(str(datetime.date.today()), date_format)
            b = datetime.datetime.strptime(str(t2.currentdate), date_format)
            t2.account_age = (a - b).days
            t2.save()
            if int(t2.account_age) >= 30 and int(t.trigger) == 0:
                t.monthly_interest_balance = (103 / 100) * float(t.interest_balance)
                t.trigger = 1
                t.save()
            if int(t2.account_age) >= 30 and int(t.trigger) == 1:
                update = priceOfGold.objects.last()
                t.interest_balance = (float(update.gold_price) / float(t.gold_price_at_creation)) * float(t.monthly_interest_balance)
                gram = (1 / update.gold_price) * float(t.monthly_interest_balance)
                t.balance_in_gold = gram
                t.save()
            if int(t2.account_age) >= 60 and int(t.trigger) == 1:
                t.monthly_interest_balance = (103 / 100) * float(t.interest_balance)
                t.trigger = 2
                t.save()
            if int(t2.account_age) >= 60 and int(t.trigger) == 2:
                update = priceOfGold.objects.last()

mysite/goldbankapp/templates/User_profile.html
{% extends 'base.html' %}

{% block content %}
<br>
<div style="color: darkblue; float:center; font-family:  Tahoma, sans-serif;">
<h2>1. <a href="/show_account_info/" style="color: blue">Account information</a></h2>
<h2>2. <a href="/show_balance_info/" style="color: blue">Account Balance information</a></h2>
<h2>3. <a href="/show_loan_info/" style="color: blue">Account Loan information</a></h2>
    <br>
<h2>4. <a href="/show_deposit_history/" style="color: blue">View my deposit records</a></h2>
<h2>5. <a href="/show_withdraw_history/" style="color: blue">View my withdraw records</a></h2>
<h2>6. <a href="/show_purchase_info/" style="color: blue">My purchases from bank</a></h2>
    <br><br>
    <a href="/features/"><button class="button" style="color: darkred;"><span>Go Back</span></button></a>
</div>
{% endblock %}

mysite/goldbankapp/templates/accountNo.html
{% extends 'base.html' %}
  {% block content %}
<section>
<!--        <h2>Welcome, <span>{{ user }}.</span></h2>-->
<!--        <h4></h4>-->
        <br>
        <div class="text-center">
            <h3>Account No.</h3>
            <h1 class="btn-info">{{ curr_user.acct_no }}</h1>
            <h4>Please note down the account no.</h4>
        </div>
        <br>
        <div class="text-center">
            <h3>Current Balance</h3>
            <h1 class="btn-info">{{ curr_user.balance }} Tk</h1>
        </div>
        <br>
    </section>
  {% endblock %}

mysite/goldbankapp/templates/buy_silver.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<body>
<div>
    {% if registered == "b" %}
    <h1 style="color: darkblue">Successfully purchased {{mydata.quantity}} Silver coins. {{mydata.price}} TK has been deducted from your account balance. Thank you for buying.</h1>
    <div style="white-space:nowrap"><h1 style="color: indigo">Check your purchase record here
        <a href="/show_purchase_info/"><button class="button" style="width: 18%; padding: 6px; color: indigo;"><span>Purchase record</span></button></a></h1>
    </div>
    {% endif %}
    {% if registered == "d" %}
    <h1 style="color: red">Purchase failed. Your account balance is insufficient.</h1>
    {% endif %}
    {% if registered == "e" %}
    <div><h1 style="color: red">Purchase failed. You did not deposit yet.</h1>
        <h1 style="color: red">Deposit here first.<a href="/depositamount/"><button class="button" style="width: 25%;  padding: 4px;"><span>Deposit</span></button></a></h1>
    </div>
    {% endif %}
    {% if registered == "c" %}
    <div style="white-space:nowrap"><h1 style="color: red">You are not registered. Register here first.
        <a href="/register/"><button class="button" style="width: 25%;  padding: 4px;"><span>Register</span></button></a></h1>
    </div>
    {% endif %}
    <h1>Buy Silver Coins here
    <img src="/static/assets/img/features/silver.png" alt="" width="75" height="75"/></h1>
    <h3 style="color: darkblue">Fill out the below form</h3>
    <br>
    <form action="{% url 'buy_silver' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="enter username"/>
        </div>
            <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="enter password"/>
        </div>
            <div class="form-group">
         <label for="quantity">Quantity:</label>
        <input type="number" name="quantity" placeholder="enter quantity"/>
        </div>
        <button class="button" style="float:middle;"><span>Buy Now</span></button>
    </form>
    <a href="/buy_product/"><button class="button" style="color: darkred;"><span>Go Back</span></button></a>
    <h4 style="color: darkred">Coin's price will be deducted from your account balance.</h4>
</div>
</body>
{% endblock %}

mysite/goldbankapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <title>Gold Bank</title>
        <link rel="icon" href="/static/assets/img/logo.jpg">
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <link href="{% static 'css/outside4.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation bar-->
        <nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
            <div class="container">
                <div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <a href="#page-top"><img src="static/assets/img/logo.jpg" alt="Logo" width="60" height="60" /></a>
    </div>
    <div class="flip-card-back">
      <a href="#page-top"><img src="static/assets/img/logo2.png" alt="Logo" width="60" height="60" /></a>
    </div>
  </div>
</div>
                <a href="#page-top"><h1 style="text-align: left; color: gold;"><span class="highlightme" style="color: gold;">&nbsp;Gold Bank&nbsp;</span></h1></a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'logout' %}" style="color: gold;">Logout</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="moneytogold/" style="color: gold;">Converter</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#" onClick="return false;" style="color: gold;">Live-Update</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team" style="color: gold;">Team</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'admin:index' %}" style="color: gold;">Admin-site</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="about/" style="color: gold;">About</a></li>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="dropdown" style="float:right">
    <span style="font-size:23px;cursor:pointer;" onclick="openNav()"><button class="dropbtn">&#9776; Menu</button></span>
    </div>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% endif %}
    <a href="/">Home</a>
    <a href="moneytogold/">Convert Money to Gold</a>
    <a href="show_gold_price/">Gold Price History</a>
    <a href="buy_product/">Buy Our Products</a>
    <a href="#" onClick="return false;">Contact</a>
<!--    <a href="features/">Services(Shortcut)</a>-->
<!--    <a href="adminPanel/">Admin Panel(Shortcut)</a>-->
</div>
<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
<script>
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
  this.classList.toggle("active");
  var dropdownContent = this.nextElementSibling;
  if (dropdownContent.style.display === "block") {
  dropdownContent.style.display = "none";
  } else {
  dropdownContent.style.display = "block";
  }
  });
}
</script>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Home-->
<!--         style="margin-top: 0px;"-->
        <header class="masthead">
            <div class="container">
                <br>
                <br>
<!--                        <form action="/action_page.php">-->
                <div class="marquee" style="white-space:nowrap; width: 240px; float: middle;">
                 <h3><z>Lastest Gold Price Update: Per One Gram Gold Price is <a style="color: orange">{{update.gold_price}} BDT</a> Updated on {{update.date}}</z></h3>
             </div>
                <div style="color:gainsboro;">
                    <h3>Like Our Facebook Page <a class="btn btn-dark btn-social mx-2" href="https://web.facebook.com/Gold-Bank-103736558274705">
                        <i class="fab fa-facebook"></i></a></h3></div>
                        <form>
                        <input type="text" placeholder="Search.." name="search">
                        <button style="color:orange;" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                <br>
                <div class="masthead-heading text-uppercase" style="color:gainsboro;">Welcome To Our Site!</div>
                {% block content %}
                <style>
                body { background-color:gainsboro; }
                .highlightme { background-color:rgba(0,0,0,.7); }
                p { background-color:#FFFFFF; }
                </style>
                <h1 style="text-align: center; color:gold;"><span class="highlightme" style="color: gainsboro; border-radius: 1px 1px 1px 1px;">&nbsp;Welcome to </span><span class="highlightme" style="color: gold;">Gold</span><span class="highlightme" style="color: gainsboro;"> Bank&nbsp;</span></h1>
                {% if user.is_authenticated %}
                    <br>
                    <a href="{% url 'logout' %}" class= "button" style="  display: block; margin: auto; width: 30%; color:black;"><span>Logout</span></a>
                {% else %}
                <br>
                <a href="{% url 'goldbankapp:user_login' %}" class= "button" style="  display: block; margin: auto; width: 30%; color:black;"><span>Login</span></a>
                {% endif %}
                <br>
                <a href="{% url 'goldbankapp:register' %}" class = "button" style="  display: block; margin: auto; width: 30%; color:black;"><span>Register (Create account)</span></a>
                <br>
                <a href="admin_login/" class = "button" style="  display: block; margin: auto; width: 30%; color:black;"><span>Admin Login</span></a>
                <br>
                <a href="myPanel/" class = "button" style="  display: block; margin: auto; width: 30%; color:black;"><span>My Panel</span></a>
                {% endblock %}
            </div>
        </header>
        <!-- Team -->
        <style>
        .img11:hover {
        opacity: 0.7;
        }
        </style>
        <section class="page-section bg-light" id="team" style="background-image: url('/static/assets/img/BDmap.jpg'); background-position: center center;
                background-size: cover;">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase" style="color: gainsboro;">Our Team</h2>
                    <h3 class="section-subheading text-muted" style="color: gainsboro;">Contributors</h3>
                    <br>
                    <br>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle img11" src="static/assets/img/team/1.jpg" alt="" />
                            <h4><span class="highlightme" style="color: dodgerblue; border-radius: 1.5px 1.5px 1.5px 1.5px;">&nbsp;Md. Ashikur Rahman&nbsp;</span></h4>
                            <div class="card" style="background-color: whitesmoke; border-radius: 5px 5px 5px 5px;">
                                <p class="text-muted" style="background-color: whitesmoke; border-radius: 5px 5px 0px 0px; padding-top: 5px;">Student</p>
                                <p class="text-muted" style="background-color: whitesmoke;">Computer Science & Engineering Department</p>
                                <p class="text-muted" style="background-color: whitesmoke;">East West University</p>
                                <p class="text-muted" style="background-color: whitesmoke; border-radius: 0px 0px 5px 5px; padding-bottom: 10px;">ashikur16jan@gmail.com</p>
                            </div>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/ashikur16jan"><i class="fab fa-facebook-messenger"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/ashikur16jan"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.whatsapp.com/?lang=en"><i class="fab fa-whatsapp"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/md-ashikur-rahman-008196215/"><i class="fab fa-linkedin"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle img11" src="static/assets/img/team/2.jpeg" alt="" />
                            <h4><span class="highlightme" style="color: dodgerblue; border-radius: 1.5px 1.5px 1.5px 1.5px;">&nbsp;Samir Asif&nbsp;</span></h4>
                            <div class="card" style="background-color: whitesmoke; border-radius: 5px 5px 5px 5px;">
                                <p class="text-muted" style="background-color: whitesmoke; border-radius: 5px 5px 0px 0px; padding-top: 5px;">Student</p>
                                <p class="text-muted" style="background-color: whitesmoke;">Computer Science & Engineering Department</p>
                                <p class="text-muted" style="background-color: whitesmoke;">East West University</p>
                                <p class="text-muted" style="background-color: whitesmoke; border-radius: 0px 0px 5px 5px; padding-bottom: 10px;">samirasif116@gmail.com</p>
                            </div>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/samir.asif.529"><i class="fab fa-facebook-messenger"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/samir.asif.529"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.whatsapp.com/?lang=en"><i class="fab fa-whatsapp"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/samir-asif-715ab51b8/"><i class="fab fa-linkedin"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle img11" src="static/assets/img/team/3.jpg" alt="" />
                            <h4><span class="highlightme" style="color: dodgerblue; border-radius: 1.5px 1.5px 1.5px 1.5px;">&nbsp;Saimun Rahman Sizan&nbsp;</span></h4>
                            <div class="card" style="background-color: whitesmoke; border-radius: 5px 5px 5px 5px;">
                                <p class="text-muted" style="background-color: whitesmoke; border-radius: 5px 5px 0px 0px; padding-top: 5px;">Student</p>
                                <p class="text-muted" style="background-color: whitesmoke;">Computer Science & Engineering Department</p>
                                <p class="text-muted" style="background-color: whitesmoke;">East West University</p>
                                <p class="text-muted" style="background-color: whitesmoke; border-radius: 0px 0px 5px 5px; padding-bottom: 10px;">sizan@gmail.com</p>
                            </div>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/SizanSiz"><i class="fab fa-facebook-messenger"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/SizanSiz"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.whatsapp.com/?lang=en"><i class="fab fa-whatsapp"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#" onClick="return false;"><i class="fab fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>